### PR TITLE
Update IabHelper.java

### PR DESCRIPTION
**Pull request by Risingson**
see https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/142

### CODE REVIEW

**Comment by olaferlandsen** [comment]
@AlexDisler please, merge it

**Comment by moritzgloeckl** [comment]
@olaferlandsen Have you tested this and can you confirm that this is working?

**Comment by olaferlandsen** [comment]
@moritzgloeckl it work for me :D 
tested on Android 4.3

**Comment by moritzgloeckl** [comment]
I've merged it.

**Pull request merged**
