### PR TITLE
Fix the target location (target-dir) of the file "IInAppBillingService.aidl" for version 7.0.0 of Android.

### PR DESCRIPTION
**Pull request by terangel**
The target directory has changed in Android 7.0.0.

### CODE REVIEW

**Comment by moritzgloeckl** [comment]
Hi, 
thanks for the PR, does this break builds on previous Android versions? I can't test right now unfortunately.

Cheers

**Comment by terangel** [comment]
Hi Moritz, 

In version 7.0.0 the project structure for Android has changed, for this reason when building the project the file "IInAppBillingService.aidl" can not be found. 

The new location for this file is: _app/src/main/aidl/com/android/vending/billing_ (from _src/com/android/vending/billing_).

Cheers.

**Comment by redeleon** [comment]
sorry, newbie here, how do I use this version? its bugging me on cli-8.0.0

**Comment by guilhermehtk** [comment]
+1

**Comment by rhclayto** [comment]
Is this good to go? +1 on this.

**Comment by EmreErdogan** [comment]
@terangel Is there a way to override this in the config.xml file of a Cordova project. Would one of **resource-file** or **config-file** tags help?  I mean the PR isn't merged, yet and not tested. But I use cordova-android 7.x. So, how can I apply your change to my project?

**Comment by terangel** [comment]
It seems that from the version 7.1.4 of Android in Cordova, the issues to locate the source files of the plugin are completely solved.

Including the location of the .aidl file and the issues in versions 7.1.2 and 7.1.3 when copying files that include the string "app" in the target directory, like "inapppurchases".

More info: https://github.com/apache/cordova-android/pull/572

**Pull request closed without merging**
